project: "VGPG"
name: "VGPG-${dataset_name}"
dataset_name: "lexica.art"
save_dir: "./style_transfer/${dataset_name}/"
save_file: "results_${dataset_name}.csv"
data_dir: ["/sdc1/datasets/lexica.art/images/0.png"]
gps: 1  # this configuration file is set for 8-GPUs
batch_size: 4
style_transfer: true
object: "A Paris"

# ---------------------------------------------------------------- #
wandb:
  mode: "disabled"
  notes: null
  id: null

seed: 12345

# ---------------------------------------------------------------- #
model:
  model_ckpt: "/sdb1/models/llama/converted-ckpt"
  load_in_8bit: true
  max_length: 32
  min_length: 32
  freeze_model: true
  gen_prompt_only: false
  num_beams: 10
  beam_expand_factor: 10
  clip_version: "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
  sd_version: "stabilityai/stable-diffusion-2-1"
  clip_ref: "ViT-g-14"
  clip_ref_pretrain: "laion2b_s12b_b42k"
  sampling: # Stable Diffusion
    steps: 25
    n_samples: 15 # how many samples to produce for each given prompt. aka batch size
    n_rows: 0 # rows in the grid
    scale: 9.0 #
  user_prompt: "Please generate the diffusion prompt of the image style based on the given condition containing the painting style, color, and shapes of the image: "
  system_prompt: "You are a respectful and honest visual description generator for Stable Diffusion text prompt. Answer in 1 sentence and do not mention anything other than prompt. Don't mention 'prompt'."
  model_prompt: " Answer: Sure, here's a prompt for stable diffusion within ${model.max_length} tokens:\n "
  get_initial_condition: true
  get_similarity: true
# ---------------------------------------------------------------- #
